apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAo6yJ9styTQ+q8nKTOgePSOdsCNJDs6afTqCrc8R/zB5AwdUJYsfnZxZQe120pa9eNtUcu5MivQ5qAvB0ZEljbS6E3fdYJgF449vf2a+i096XQyCF1HSY9edQeQcOUolSyMXy88Qc1TukfZsMx5w8428pI9XxHIaFRB8B3RxS09AT6uDhb0fd7AKaFc9F6dtDiNGfC7BBTGqxq2EBKkHCINlTCEcKpxZEm/T6TtbmNb3ONxKKn7V2/ryHaObuqg2TszPm9f1ix/kdP2g3cwS79HFGQKSax/aqaWr5FTB7U8S8Sst/7leQZed2sEZBTiRLAY1QzF5PlQLFa47Mi9eKKvk1eCHGW7eiiv39MvO3eounvI9d1IQOsAejHiuIbQkSFIJG78yCEnRy713tT1Q/sa0B2GO3VowKo3IzFKoQp1BBSMHcdRYs+vUX76Oi9bu7o35g6iSDhZFMweBQi/whSFP6+Tn5u59wkai86qtLDQURKdV+UEkLWHJHWkC/XMSqJ3YELotd3Q6ic1N11wZHSkz4ASKlUP0ENf0SOgu8Qq5OGFfbcVkmd+feedT0Z8uXk/TKA8KuBe8hku9r/zSO8cYIUXK8w2MPoKLva6gpAL7M2+d7651NXyg2uxe1hK+te1G8AL1gNR3kFrqOoBDvZk37+6iIvKkOi//2Cx2p/loXIG0XkFeBoWWjZsSMhgw9PRbF7ZPJUtg==
    DB_USER: AgAGEDxyUo20/fOgIvbn3wCGiUquUKtHOnH6w5fXqzND/l6sEsljWLBQSQSjkf7MmkT1PjZi1U4qMtByYDUiMhkhtf0MHfIZVWMNTKKqNIveM/1nPRdewCmk122agv/WFmXDOZGu3Rcm+BdiCCE1VJVUXpAdWId1ATB3O2HmY9NFHJDzBFWbFsnUynZGH9t/jPRYhowc8gXUG8Dulb3GqcgnPApdUTtEPiL1HrYrCx7FZW8I7rGnW6TbwhVaJQ4WNlVumKqYuFe7A5qJqVLNU03rKkei32M6Z9txWediXkD1I0qdMhILxNafosDLT/kP2+TFm4GBDJk+/oPYX0N4XvaaLqxsDuT4ytiXt7/sR6tzkk+lbUNF4bVgO53b5ZW87vKCLhKkQ4DLtjF8lrxIw4DGykx59nW7tZ+gOSXL4nAWmDwR5nhjImWbrSnvxqTz/ofZG7ym88aSIewBUUEu//oWgaW/ROpZnUxQY4FLu8qghF4X6y9jyMkU0lGlwq8fzAWVRNxZQHpHKmDmEIzRb6HyYPveKjSrPjNOLR5SuYjb29zl/7RwBObAJfNU4QAahYu5PgYZ8Zg5pPAQ5kMNrM+pBv1EaUsjtST4M7Buh5kqupzgF8B7o9MOex1LA80A+coprx9lZeSBSnplZJxBE+DSI+FmAAmsZ0HY11TEm9eHgBrnj0KVIxLFM3/u57sluj215ES/2hdyLw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

